import{i as c,S as h,a as w}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();let d="",y=1;const g=document.querySelector(".search-form"),p=document.querySelector(".gallery"),a=document.querySelector(".loader"),i=document.querySelector(".load-more");a.style.display="none";const b="https://pixabay.com/api/";let u;g.addEventListener("submit",s=>{s.preventDefault(),a.style.display="block";const r=s.target.elements.query.value.trim();if(r.length<3){c.warning({title:"Warning",message:"Please enter a search query with at least 3 characters.",position:"topRight"}),a.style.display="none";return}i.style.display="none",d=r,y=1,p.innerHTML="",m(d,y).then(({hits:o})=>{if(o.length>0){const n=o.map(f).join("");p.innerHTML=n,u=new h(".gallery-link"),u.refresh(),a.style.display="none"}else c.info({title:"Info",message:"Unfortunately, no images were found for your search. Please try again!",position:"topRight"}),i.style.display="none"}),g.reset()});i.addEventListener("click",async()=>{a.style.display="block",y+=1;const{hits:s}=await m(d,y),r=s.map(f).join("");p.insertAdjacentHTML("beforeend",r),u.refresh(),a.style.display="none",s.length===0&&(i.style.display="none",c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),window.scrollBy({top:document.querySelector(".gallery-image").getBoundingClientRect().height*2,behavior:"smooth"})});async function m(s,r=1){const o={key:"42392659-652aaf55959599f1a779f61b5",q:s,image_type:"photo",orientation:"horizontal",safeSearch:!0,per_page:15,page:r},n=b+"?"+new URLSearchParams(o).toString();try{const e=await w.get(n);if(e.data.totalHits<=o.per_page*o.page?i.style.display="none":i.style.display="block",e.status!==200)throw new Error("Network response was not ok");return e.data}catch(e){throw c.error({title:"Error",message:"There seems to be a problem with your internet connection. Please check and try again.",position:"topRight"}),e}finally{a.style.display="none"}}function f({largeImageURL:s,tags:r,webformatURL:o,likes:n,views:e,comments:t,downloads:l}){return`
    <a href="${s}" class="gallery-link">
      <figure>
        <img src="${o}" alt="${r}" class="gallery-image">
        <figcaption class="gallery__figcaption">
          <div class="image-item">Likes <span class="image-elem">${n}</span></div>
          <div class="image-item">Views <span class="image-elem">${e}</span></div>
          <div class="image-item">Comments <span class="image-elem">${t}</span></div>
          <div class="image-item">Downloads <span class="image-elem">${l}</span></div>
        </figcaption>
      </figure>
    </a>
  `}
//# sourceMappingURL=commonHelpers.js.map
